# Build settings
permalink: /blog/:year/:title/
gems: [jekyll-paginate]

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
highlighter: rouge

paginate: 10
paginate_path: '/blog/page/:num/'
comments: true

collections:
  works:
    output: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Steven Hubert | Digital Product &amp; UX | NYC Bred, Denver Based
description: 'Digital leader with 20 years experience leading UX and Product product teams both agency and client side.'
keywords: 'steven hubert, denver, colorado, marketing, technology, advertising, project management, digital producer'
url: https://www.stevenhubert.com
baseurl: ''

google_analytics: UA-1735487-1

# Author settings
author:
  name: Steven Hubert
  job: Digital Product and UX leader
  bio: 'I enthusiastically bridge the divide between IT, Marketing and AdTech by implementing new technologies and novel work approaches to deliver meaningful content to customers and businesses alike.'
  thumb: /images/sh.jpg

  url: https://www.stevenhubert.com
  github: http://github.com/hubertron
  twitter: http://twitter.com/stevenhubertron
  linkedin: http://linkedin.com/in/stevenhubert

# navbar pages
navbar:
  - slug: about
    title: About

exclude:
  [
    'gulp',
    'node_modules',
    'bower',
    'bower_components',
    'config.rb',
    'src',
    'Gemfile',
    'Gemfile.lock',
    '.rvmrc',
    '.rbenv-version',
    'package.json',
    'gulpfile.js',
    'README.md',
    'Rakefile',
    'changelog.md',
  ]
